name: Uzak Baglanti derle

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  derle:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "surum"
